version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
        - 27017:27017
  notebook:
    build: .
    container_name: python
    ports:
     - "8888:8888"
     - "5066:5066"
    command: ["pipenv", "run", "jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    volumes:
      - ./:/home/dev/code/
  selenium-firefox:
    image: selenium/standalone-firefox
    container_name: selenium-firefox
    ports: 
      - "4444:4444"
    environment:
      - SE_NODE_SESSION_TIMEOUT=10000
    network_mode: host
    shm_size: 2g